### ISSUE TITLE
Add guidance on converting a JSON payload to vc-jwt payload

### ISSUE THREAD

**Issue by georgepadayatti** [w3c/vc-jwt#108]
It is unclear from the document, how to convert a JSON payload to vc-jwt.

**Comment by OR13** [comment]
its likely not going to be made clear in this document, see:

- https://github.com/w3c/vc-jwt/pull/88
- https://github.com/vcstuff/draft-terbu-sd-jwt-vc

This document focuses on JSON-LD, the one at IETF will cover regular json.

There won't be conversion, because its either done before you get JSON-LD you want to secure, or not at all because you hate JSON-LD :)

hope that helps.
